### ISSUE TITLE
Kai Workspace Design

### ISSUE THREAD

**Issue by Grismund** [Grismund/game-kai-workspace#1]
# Kai Workspace: Design Doc

## TODO:
- [x] Only render items in the inventory if they are "Obtained"
  - I had to create a new ObservableCollection in the ViewModel which builds itself based on `ItemStatus`
  - The `ItemSource` in the xaml then needs to bind to `ObtainedItems`.
```csharp
        public ObservableCollection<Item> ObtainedItems  => new ObservableCollection<Item>(Items.Where(item => item.Status == Item.ItemStatus.Obtained));
```
- [x] Hook `obtained` items in the model up to the inventory. *passing data through a Viewmodel*
  - [x] The Xaml needed a databinding. Seems very clunky, but **I couldn't get it to work in the code-behind.**
```xaml
    <ContentPage.BindingContext>
        <viewModels1:ItemsViewModel />
    </ContentPage.BindingContext>
```

- [x] Set the `ItemStatus` property from `Unobtained` to `Obtained` when `Picker` option is selected. *Event handlers setting properties through a ViewModel*
- [x] Connect Images to items somehow. *How to connect a List to assets*
- [ ] `Use` in Inventory which: 
  - [ ] Displays a story snippet about what happens when you use it. *Modal over Modal?*
  - [ ] Sets `ItemStatus` to `Used` which removes it from the inventory *Event handler and logic in the ViewModel*
- [ ] Save Inventory locally *Access Device*
- [ ] Fade text in `OnPropertyChanged` or `OnComponenetLoad` or whatever. *Event handlers and component lifecycle*

## Questions
- How would I conditionally render items without a bunch of logic in the view layer? Codebehind? ViewModel?
  - Answer: Create a new `ObservableCollection` in the ViewModel.
- How do I reference the instantiated `Items` list throughout the app once it is instantiated?
  - **Problem** I was initializing the inventory only when the Modal loaded. That meant that I could not get/set Items on the main screen.
  - **Solution** 
### 1. Instantiate the viewModel when the main page initializes
  ```csharp
         public MainPage()
         {
             InitializeComponent();
             
             viewModel = new ItemsViewModel();
         }
  ```
### 2. Pass the `viewModel` as a parameter to the new instantiation of the Modal with a button click.
```csharp
        async void OnButtonClicked(object sender, EventArgs e)
        {
           await Navigation.PushModalAsync(new InventoryModal(this.viewModel));
        }
```
### 3. Set the BindingContext of the InventoryModal to the current instance of the viewModel that was passed to it
```csharp
        public InventoryModal(ItemsViewModel viewModel)
        {
            InitializeComponent();
            BindingContext = viewModel;
        }
```

- If I update an item in the `ObservableCollection Items`, will it automatically update the `ObservableCollection ObtainedItems`?
- Why are there two mutually exclusive issues with this....
  - If I include `x:DataType=viewModels:ItemsViewModel` in the `InventoryModal.xaml`, it won't load, and I get this error: 
![image](https://github.com/Grismund/game-kai-workspace/assets/81186833/d1a2c836-0b67-45d9-8248-6f19ed5d19ba)
  - If I don't include that, everything runs fine, but my intellisense can't pick up the BindingContext: 
![image](https://github.com/Grismund/game-kai-workspace/assets/81186833/45fda353-59b3-4108-a81c-af0b945ce7c8)
🤔

## Approaches
Set `Item.ItemStatus` to `Obtained` when `OptionSelected` changes.
- Done in the `OptionSelected` method itself
- Create a class that consumes the raw data and filters it. Have the data binding set to what that converter returns.
- Save Data Locally
  - ~~`ILocalDataService` eg. (`ILocalDataService` `localDataService.SaveDataAsync(LocalDataKey.Items, json)`). We already use this pattern in the app, so it's useful to know, but also very samey.~~
  - SqLite database on the phone. This option isn't used by us, so it would be cool to do it!
  -  [ ] Install SQLite NuGet

## Implementation
- [ ] There's some ickiness in the way the Picker and the Items are connected. If the Picker order or the Item order changes AT ALL, it completely messes everything up. Probably the Picker options should be in the database as well.
  - Rooms many to one PickerOptions.
  - PickerOptions many to many Items.
